var spellings_data = {
    // spellings: ["Apple", "Ball", "Cat", "Dog", "Elephant", "Frog", "Goat", "Hen", "Ink", "Jaguar", "Kangaroo", "Leopard", "Monkey", "Nest", "Owl", "Parrot", "Queen", "Rabbit", "Sloth", "Tiger", "Umbrella", "Vulture", "Wolf", "Xmas Tree", "Yak", "Zebra"],
    spellings: ['Apple', 'Bus', 'Cat', 'Dog', 'Elephant', 'Fish', 'Goat', 'Horse', 'Inkpot', 'Jeep', 'Kite', 'Lemon', 'Mango', 'Nail', 'Ox', 'Parrot', 'Queen', 'Rabbit', 'Squirrel', 'Tree', 'Umbrella', 'Vegetables', 'Window', 'Xmas Tree', 'Yark', 'Zebra'],
    images: [
        "https://i.imgur.com/0VpjvPk.jpg",
        "https://i.imgur.com/nQwvyIS.png",
        "https://i.imgur.com/9q4vOke.png",
        "https://i.imgur.com/CeawXKd.jpg",
        "https://i.imgur.com/1mWH87a.png",
        "https://i.imgur.com/DgBviR0.jpg",
        "https://i.imgur.com/UgqBbhB.png",
        "https://i.imgur.com/eHGCoEx.jpg",
        "https://i.imgur.com/kFbaCdX.jpg",
        "https://i.imgur.com/wsUrpWg.png",
        "https://i.imgur.com/OKbcup4.png",
        "https://i.imgur.com/Z4NNq1A.png",
        "https://i.imgur.com/bWylvCB.png",
        "https://i.imgur.com/4yiRcbu.png",
        "https://i.imgur.com/YqJNKLH.png",
        "https://i.imgur.com/GaVCRsO.png",
        "https://i.imgur.com/fAz29oO.jpg",
        "https://i.imgur.com/17TJWzv.png",
        "https://i.imgur.com/C2fbrAI.png",
        "https://i.imgur.com/mr9MyGJ.png",
        "https://i.imgur.com/vmISIH8.jpg",
        "https://i.imgur.com/LG3xR6O.png",
        "https://i.imgur.com/q5fUh83.png",
        "https://i.imgur.com/5w6fZsD.png",
        "https://i.imgur.com/FPmvN8p.jpg",
        "https://i.imgur.com/r1dqart.jpg"
    ],
}